---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-workflows
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/mhumesf/hundreds-of-clusters-demo.git
    # Load from HEAD not the PR for security purposes due to the elevated permissions
    targetRevision: HEAD
    path: apps/cluster-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
